version: '3.7'

services:
  database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todolist
    ports:
      - "2043:3306"
    volumes:
      - ../database/API-BileMo:/var/lib/mysql
