version: '3.7'

services:
  database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todolist
    ports:
      - "2043:3306"
    volumes:
      - ../database/todolist:/var/lib/mysql
  test_database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: passwordtest
      MYSQL_DATABASE: todolisttest
    ports:
      - "9080:3306"
    volumes:
      - ../database/todolisttest:/var/lib/mysql
